# Generated by Django 2.2.13 on 2021-01-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_data',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
